#
# Copyright (c) 2013 by Pawel Tomulik <pawel.tomulik@pw.edu.pl>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE


Import('env')

env.Tool('texas')

# TODO: uncomment if you wish to use gnuplot
# env.Tool('gnuplot')

# TODO: add dependencies that are not discovered by SCons LaTeX SCanner.
deps = ['sin.eps']

# TODO: If you wish to import files from our local TeX Directory Structure
# deps += env.TeXASImport( ['$NAME.cls'], progname = 'latex',
#                KPSVARIABLES = {'TEXMFHOME' : '../../../../share/texmf:'} )

name = '$NAME'

dvi = env.TeXASDVI(name, deps = deps)
pdf = env.TeXASDVIPDFM(name, dvi)
src = env.TeXASChildren(dvi)
tgz = env.TeXASTarGz(name, src, strip_dirs = '..')

env.Alias(name, dvi + pdf + tgz)
env.AlwaysBuild(name)

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=python expandtab tabstop=4 shiftwidth=4:
